Completely reworked the whole of console
Changed everything to functions to allow for modularity.
Changed command sytax (swapped) to be like systemd.
Added a proper console window with GNU screen (lives up to its name).
Removed StarMade code, as it was never used.
Other cleanup.

diff --git a/listener b/listener
--- a/listener
+++ b/listener
@@ -24,7 +24,7 @@ if [ -z "$PROFILE" ]; then
     exit 1
 fi
 
-$PROFILE || { echo "Profile ${PROFILE} was not found. Run console config to add it"; exit 1; }
+$PROFILE || { echo "Profile ${PROFILE} was not found. Run console add <type> to add it"; exit 1; }
 
 ## Regexes
 # Player event:
