Updated listener with better varnames and matching
Updated vars with lower_case for all vars.
Left constants as UPPER_CASE.
Made patterns better for older and forge servers.
Added comments about 1.7.X incompatabilities.

diff --git a/listener b/listener
--- a/listener
+++ b/listener
@@ -1,10 +1,9 @@
 #!/bin/bash
 
-VERSION="3.0"
-
+VERSION="4.0"
 USERNAME=$(whoami)
-
 CONFIG_FILE="/home/$USERNAME/.config/java_console.config"
+
 if ! [ -e "${CONFIG_FILE}" ]; then
     echo "No config file was found"
     echo "Please run console config to make one"
@@ -15,16 +14,16 @@ find_jar() {
     : # Need blank function to prevent errors
 }
 
-source "$CONFIG_FILE"
-PROFILE="$1"
+source "${CONFIG_FILE}"
+profile="$1"
 
-if [ -z "$PROFILE" ]; then
+if [ -z "${profile}" ]; then
     echo "Pass a profile name in as the argument"
     echo "Example: $0 vanilla"
     exit 1
 fi
 
-$PROFILE || { echo "Profile ${PROFILE} was not found. Run console add <type> to add it"; exit 1; }
+${profile} >& /dev/null || { echo "Profile ${profile} was not found. Run console add <type> to add it"; exit 1; }
 
 ## Regexes
 # Player event:
@@ -32,12 +31,13 @@ $PROFILE || { echo "Profile ${PROFILE} was not found. Run console add <type> to 
 # Player chat:
 # \[(?:[0-9]{2}:*){3}\]\ \[Server\ thread\/INFO\]:\ <(?:\§[0-9a-r])?([0-9a-zA-Z_]+)(?:\§[0-9a-r])?> (.*)
 
-FILE="${SERVERPATH}/logs/latest.log"
+LOG_FILE="${server_path}/logs/latest.log"
+# Won't work on 1.7.X, but it won't do any harm either
 FIREWORK="~ ~ ~ summon FireworksRocketEntity ~ ~ ~ {LifeTime:20,FireworksItem:{id:fireworks,Count:1,tag:{Fireworks:{Explosions:[{Type:1,Flicker:0,Trail:1,Colors:[2723327,13565739],FadeColors:[13344511]}]}}}}"
-CHATFILE="${SERVERPATH}/logs/chat.log"
-MINECRAFTMAP="/home/mark/bin/minecraftmap request"
-LOGINMESSAGE="Welcome to Rycieos' jaguar Minecraft server!"
-TIMES="${SERVERPATH}/times"
+CHAT_FILE="${server_path}/logs/chat.log"
+MINECRAFT_MAP_COMMAND="/home/mark/bin/minecraftmap request"
+LOGIN_MESSAGE="Welcome to Rycieos' jaguar Minecraft server!"
+TIMES_PATH="${server_path}/times"
 
 # What is run when players say "!info" in chat. $1 is player name.
 info() {
@@ -47,28 +47,28 @@ info() {
 }
 
 ops() {
-    OPS=$(grep "name" "${SERVERPATH}"/ops.json | sed 's/    "name": "\([a-zA-Z0-9_.-][a-zA-Z0-9_.-]*\)",/\1/')
-    OPS=$(echo "$OPS" | tr '\n' ' ' | sed -e 's/^ *//' -e 's/ *$//' -e 's/ /\|/g')
-    echo "ops: $OPS"
+    ops=$(grep "name" "${server_path}"/ops.json | sed 's/    "name": "\([a-zA-Z0-9_.-][a-zA-Z0-9_.-]*\)",/\1/')
+    ops=$(echo "${ops}" | tr '\n' ' ' | sed -e 's/^ *//' -e 's/ *$//' -e 's/ /\|/g')
+    echo "ops: ${ops}"
 }
 
 players() {
-    NUMPLAYERS=$(command "list" && sleep 2 && grep "players online" "${FILE}" | tail -1 | sed 's/.*\([0-9]\+\)\/[0-9].*/\1/')
+    num_players=$(command "list" && sleep 2 && grep "players" "${LOG_FILE}" | grep "online" | tail -1 | sed 's/.*\ \([0-9]\+\).*/\1/')
 }
 
 say() {
     # Sends the contents to the screen and prints it as the server
-    screen -p 0 -S "$PROFILE" -X stuff "say $*$(printf \\r)"
+    screen -p 0 -S "${profile}" -X stuff "say $*$(printf \\r)"
 }
 
 text() {
     # Sends the contents to the screen as pure text to a specific player
-    screen -p 0 -S "$PROFILE" -X stuff "tellraw $1 {\"text\":\"${*:2}\"}$(printf \\r)"
+    screen -p 0 -S "${profile}" -X stuff "tellraw $1 {\"text\":\"${*:2}\"}$(printf \\r)"
 }
 
 command() {
     # Sends the contents to the screen and executes it
-    screen -p 0 -S "$PROFILE" -X stuff "$*$(printf \\r)"
+    screen -p 0 -S "${profile}" -X stuff "$*$(printf \\r)"
 }
 
 is_running() {
@@ -82,128 +82,142 @@ is_running() {
     fi
 }
 
-READLINES=$(wc -l < "${FILE}")
+read_lines=$(wc -l < "${LOG_FILE}")
 ops
 while true; do
-    LINES=$(wc -l < "${FILE}")
+    lines=$(wc -l < "${LOG_FILE}")
     
-    if [ "$READLINES" -gt "$LINES" ]; then
-        ((READLINES = ( $LINES - 1 ) ))
+    # If the log file has been reset
+    if [ "${read_lines}" -gt "${lines}" ]; then
+        ((read_lines = ( ${lines} - 1 ) ))
     fi
     
-    while [ "$READLINES" -lt "$LINES" ]; do
-        ((READLINES += 1))
-        CURRENTLINE=$(sed "${READLINES}q;d" "${FILE}")
-        echo "${READLINES}: ${CURRENTLINE}"
+    while [ "${read_lines}" -lt "${lines}" ]; do
+        ((read_lines += 1))
+        current_line=$(sed "${read_lines}q;d" "${LOG_FILE}")
+        echo "${read_lines}: ${current_line}"
 
-        if echo "${CURRENTLINE}" | grep -q "\[\([0-9]\{2\}:*\)\{3\}\]\ \[Server\ thread/INFO\]:\ \(\§[0-9a-r]\)\?[0-9a-zA-Z_]\+\(\§[0-9a-r]\)\? "; then
-            PLAYER=$(echo "${CURRENTLINE}" | sed 's|\[\([0-9]\{2\}:*\)\{3\}\]\ \[Server\ thread/INFO\]:\ \(\§[0-9a-r]\)\?\([0-9a-zA-Z_]\+\)\(\§[0-9a-r]\)\? \(.*\)|\3|')
-            MESSAGELINE=$(echo "${CURRENTLINE}" | sed 's|\[\([0-9]\{2\}:*\)\{3\}\]\ \[Server\ thread/INFO\]:\ \(\§[0-9a-r]\)\?\([0-9a-zA-Z_]\+\)\(\§[0-9a-r]\)\? \(.*\)|\5|')
+        if echo "${current_line}" | grep -q "\[\([0-9]\{2\}:*\)\{3\}\]\ \[Server\ thread/INFO\]:\ \(\§[0-9a-r]\)\?[0-9a-zA-Z_]\+\(\§[0-9a-r]\)\? "; then
+            player=$(echo "${current_line}" | sed 's|\[\([0-9]\{2\}:*\)\{3\}\]\ \[Server\ thread/INFO\]:\ \(\§[0-9a-r]\)\?\([0-9a-zA-Z_]\+\)\(\§[0-9a-r]\)\? \(.*\)|\3|')
+            message_line=$(echo "${current_line}" | sed 's|\[\([0-9]\{2\}:*\)\{3\}\]\ \[Server\ thread/INFO\]:\ \(\§[0-9a-r]\)\?\([0-9a-zA-Z_]\+\)\(\§[0-9a-r]\)\? \(.*\)|\5|')
 
-            if echo "${MESSAGELINE}" | grep -q "joined the game"; then
-                echo "$(date +%x-%X) ${PLAYER} joined the game" >> "${CHATFILE}"
+            if echo "${message_line}" | grep -q "joined the game"; then
+                echo "$(date +%x-%X) ${player} joined the game" >> "${CHAT_FILE}"
                 players
-                text "$PLAYER" "$LOGINMESSAGE"
+                text "${player}" "${LOGIN_MESSAGE}"
 
-                if [ -s "${TIMES}/${PLAYER}.time" ]; then
-                    TIME=$(cat "${TIMES}/${PLAYER}.time")
-                    text "$PLAYER" "You were last logged in at ${TIME}"
+                if [ -s "${TIMES_PATH}/${player}.time" ]; then
+                    time=$(cat "${TIMES_PATH}/${player}.time")
+                    text "${player}" "You were last logged in at ${time}"
                 else
-                    text "$PLAYER" "This is your first time on this server!"
-                    command "execute ${PLAYER}" "$FIREWORK"
+                    text "${player}" "This is your first time on this server!"
+                    command "execute ${player}" "${FIREWORK}"
                 fi
 
-                if [ "$NUMPLAYERS" -lt 2 ]; then
-                    TIME=$(cat "${TIMES}/latest")
-                    text "$PLAYER" "The last time someone was online was ${TIME}"
+                if [ "${num_players}" -lt 2 ]; then
+                    time=$(cat "${TIMES_PATH}/latest")
+                    text "${player}" "The last time someone was online was ${time}"
                 else
-                    text "$PLAYER" "There are ${NUMPLAYERS} players online right now"
+                    text "${player}" "There are ${num_players} players online right now"
                 fi
 
-                text "$PLAYER" "For more info about the server and its features, say !help in chat"
+                text "${player}" "For more info about the server and its features, say !help in chat"
             fi
 
-            if echo "${MESSAGELINE}" | grep -q "left the game"; then
-                echo "$(date +%x-%X) ${PLAYER} left the game" >> "${CHATFILE}"
-                date +%-a\ %-b\ %-e,\ %-l:%M\ %p\ %Y > "${TIMES}/${PLAYER}.time"
-                echo "${PLAYER} at $(cat "${TIMES}/${PLAYER}.time")" > "${TIMES}/latest"
+            if echo "${message_line}" | grep -q "left the game"; then
+                echo "$(date +%x-%X) ${player} left the game" >> "${CHAT_FILE}"
+                date +%-a\ %-b\ %-e,\ %-l:%M\ %p\ %Y > "${TIMES_PATH}/${player}.time"
+                echo "${player} at $(cat "${TIMES_PATH}/${player}.time")" > "${TIMES_PATH}/latest"
             fi
     
-        elif echo "${CURRENTLINE}" | grep -E -i -q "(Opped |De-opped )"; then
+        elif echo "${current_line}" | grep -E -i -q "(Opped |De-opped )"; then
             # Someone was opped, reload our list
             ops
         fi
 
         # Quit if not chat
-        if echo "${CURRENTLINE}" | grep -q "\[\([0-9]\{2\}:*\)\{3\}\]\ \[Server\ thread/INFO\]:\ <\(\§[0-9a-r]\)\?[0-9a-zA-Z_]\+\(\§[0-9a-r]\)\?> "; then
-            PLAYER=$(echo "${CURRENTLINE}" | sed 's|\[\([0-9]\{2\}:*\)\{3\}\]\ \[Server\ thread/INFO\]:\ <\(\§[0-9a-r]\)\?\([0-9a-zA-Z_]\+\)\(\§[0-9a-r]\)\?> \(.*\)|\3|')
-            CHATLINE=$(echo "${CURRENTLINE}" | sed 's|\[\([0-9]\{2\}:*\)\{3\}\]\ \[Server\ thread/INFO\]:\ <\(\§[0-9a-r]\)\?\([0-9a-zA-Z_]\+\)\(\§[0-9a-r]\)\?> \(.*\)|\5|')
+        if echo "${current_line}" | grep -q "\[\([0-9]\{2\}:*\)\{3\}\]\ \[Server\ thread/INFO\]:\ \(\[Server\]\ \)\?<\(\§[0-9a-r]\)\?[0-9a-zA-Z_]\+\(\§[0-9a-r]\)\?> "; then
+            player=$(echo "${current_line}" | sed 's|\[\([0-9]\{2\}:*\)\{3\}\]\ \[Server\ thread/INFO\]:\ \(\[Server\]\ \)\?<\(\§[0-9a-r]\)\?\([0-9a-zA-Z_]\+\)\(\§[0-9a-r]\)\?> \(.*\)|\4|')
+            chat_line=$(echo "${current_line}" | sed 's|\[\([0-9]\{2\}:*\)\{3\}\]\ \[Server\ thread/INFO\]:\ \(\[Server\]\ \)\?<\(\§[0-9a-r]\)\?\([0-9a-zA-Z_]\+\)\(\§[0-9a-r]\)\?> \(.*\)|\6|')
 
-            echo "$(date +%x-%X) <${PLAYER}> ${CHATLINE}" >> "${CHATFILE}"
+            echo "$(date +%x-%X) <${player}> ${chat_line}" >> "${CHAT_FILE}"
         else
             continue
         fi
 
-        if echo "${CHATLINE}" | grep -q "kappa"; then
-            text "@a" "░░░░▄▀▀▀▀▀█▀▄▄▄▄░░░░\n░░▄▀▒▓▒▓▓▒▓▒▒▓▒▓▀▄░░\n▄▀▒▒▓▒▓▒▒▓▒▓▒▓▓▒▒▓█░\n█▓▒▓▒▓▒▓▓▓░░░░░░▓▓█░\n█▓▓▓▓▓▒▓▒░░░░░░░░▓█░\n▓▓▓▓▓▒░░░░░░░░░░░░█░\n▓▓▓▓░░░░▄▄▄▄░░░▄█▄▀░\n░▀▄▓░░▒▀▓▓▒▒░░█▓▒▒░░\n▀▄░░░░░░░░░░░░▀▄▒▒█░\n░▀░▀░░░░░▒▒▀▄▄▒▀▒▒█░\n░░▀░░░░░░▒▄▄▒▄▄▄▒▒█░\n░░░▀▄▄▒▒░░░░▀▀▒▒▄▀░░\n░░░░░▀█▄▒▒░░░░▒▄▀░░░\n░░░░░░░░▀▀█▄▄▄▄▀░░░░"
+        if echo "${chat_line}" | grep -q "kappa"; then
+            text "@a" "░░░░▄▀▀▀▀▀█▀▄▄▄▄░░░░"
+            text "@a" "░░▄▀▒▓▒▓▓▒▓▒▒▓▒▓▀▄░░"
+            text "@a" "▄▀▒▒▓▒▓▒▒▓▒▓▒▓▓▒▒▓█░"
+            text "@a" "█▓▒▓▒▓▒▓▓▓░░░░░░▓▓█░"
+            text "@a" "█▓▓▓▓▓▒▓▒░░░░░░░░▓█░"
+            text "@a" "▓▓▓▓▓▒░░░░░░░░░░░░█░"
+            text "@a" "▓▓▓▓░░░░▄▄▄▄░░░▄█▄▀░"
+            text "@a" "░▀▄▓░░▒▀▓▓▒▒░░█▓▒▒░░"
+            text "@a" "▀▄░░░░░░░░░░░░▀▄▒▒█░"
+            text "@a" "░▀░▀░░░░░▒▒▀▄▄▒▀▒▒█░"
+            text "@a" "░░▀░░░░░░▒▄▄▒▄▄▄▒▒█░"
+            text "@a" "░░░▀▄▄▒▒░░░░▀▀▒▒▄▀░░"
+            text "@a" "░░░░░▀█▄▒▒░░░░▒▄▀░░░"
+            text "@a" "░░░░░░░░▀▀█▄▄▄▄▀░░░░"
 
-        elif echo "${CHATLINE}" | grep -q "^!playerinfo"; then
-            LOOKUPPLAYER=$(echo "${CHATLINE}" | sed 's|!playerinfo \([0-9a-zA-Z_]\+\)\ *.*|\1|')
-            if [ -s "${TIMES}/${LOOKUPPLAYER}.time" ]; then
-                TIME=$(cat "${TIMES}/${LOOKUPPLAYER}.time")
-                text "$PLAYER" "${LOOKUPPLAYER} was last logged in at ${TIME}"
+        elif echo "${chat_line}" | grep -q "^!playerinfo"; then
+            lookup_player=$(echo "${chat_line}" | sed 's|!playerinfo \([0-9a-zA-Z_]\+\)\ *.*|\1|')
+            if [ -s "${TIMES_PATH}/${lookup_player}.time" ]; then
+                time=$(cat "${TIMES_PATH}/${lookup_player}.time")
+                text "${player}" "${lookup_player} was last logged in at ${time}"
             else
-                text "$PLAYER" "${LOOKUPPLAYER} was not found. Useage: !playerinfo PlayerName"
+                text "${player}" "${lookup_player} was not found. Useage: !playerinfo PlayerName"
             fi
 
-        elif echo "${CHATLINE}" | grep -q "^!playerlist"; then
-            text "$PLAYER" "Whitelist:"
-            WHITELIST=$(cat "${SERVERPATH}/whitelist.json" | grep '"name": ' | sed 's|    "name": "\([0-9a-zA-Z_]\+\)"|\1,|' | tr '\n' ' ')
-            text "$PLAYER" "$WHITELIST"
+        elif echo "${chat_line}" | grep -q "^!playerlist"; then
+            text "${player}" "Whitelist:"
+            whitelist=$(cat "${server_path}/whitelist.json" | grep '"name": ' | sed 's|    "name": "\([0-9a-zA-Z_]\+\)"|\1,|' | tr '\n' ' ')
+            text "${player}" "${whitelist}"
         
-        elif echo "${CHATLINE}" | grep -q "^!firework"; then
-            text "$PLAYER" "Fine."
-            command "execute ${PLAYER}" "$FIREWORK"
+        elif echo "${chat_line}" | grep -q "^!firework"; then
+            text "${player}" "Fine."
+            command "execute ${player}" "${FIREWORK}"
 
-        elif echo "${CHATLINE}" | grep -q "^!maprequest"; then
+        elif echo "${chat_line}" | grep -q "^!maprequest"; then
             if is_running "updatemap"; then
-                text "$PLAYER" "A map update is already running. Please wait for the current one to finish."
+                text "${player}" "A map update is already running. Please wait for the current one to finish."
             else
                 say "Updating online map."
-                screen -dmS "updatemap" $MINECRAFTMAP &
+                screen -dmS "updatemap" ${MINECRAFT_MAP_COMMAND} &
             fi
 
-        elif echo "${CHATLINE}" | grep -q "^!info"; then
-            info "$PLAYER"
+        elif echo "${chat_line}" | grep -q "^!info"; then
+            info "${player}"
 
-        elif echo "${CHATLINE}" | grep -q "^!help"; then
-            text "$PLAYER" "Server command list:"
-            text "$PLAYER" "!help    view this help menu"
-            text "$PLAYER" "!info    view server info"
-            text "$PLAYER" "!playerinfo PlayerName   display last login time of PlayerName"
-            text "$PLAYER" "!playerlist    display the server whitelist"
-            text "$PLAYER" "!maprequest    update the online map"
+        elif echo "${chat_line}" | grep -q "^!help"; then
+            text "${player}" "Server command list:"
+            text "${player}" "!help    view this help menu"
+            text "${player}" "!info    view server info"
+            text "${player}" "!playerinfo PlayerName   display last login time of PlayerName"
+            text "${player}" "!playerlist    display the server whitelist"
+            text "${player}" "!maprequest    update the online map"
 
-        elif echo "${CHATLINE}" | grep -q "^!"; then
-            COMMAND=$(echo "${CHATLINE}" | sed 's|!\([a-zA-Z0-9_]\+\)\ *.*|\1|')
-            text "$PLAYER" "${COMMAND} is not a recognized command. Use !help for a list of commands"
+        elif echo "${chat_line}" | grep -q "^!"; then
+            command=$(echo "${chat_line}" | sed 's|!\([a-zA-Z0-9_]\+\)\ *.*|\1|')
+            text "${player}" "${command} is not a recognized command. Use !help for a list of commands"
 
-        elif echo "${CHATLINE}" | grep -i "server" | grep -i "how many" | grep -i -q "players are"; then
+        elif echo "${chat_line}" | grep -i "server" | grep -i "how many" | grep -i -q "players are"; then
             players
-            say "There are $NUMPLAYERS in the game."
+            say "There are ${num_players} in the game."
 
-        elif echo "${CHATLINE}" | grep -i "what" | grep -i "you say" | grep -i -q "server"; then
+        elif echo "${chat_line}" | grep -i "what" | grep -i "you say" | grep -i -q "server"; then
             say "Unfortunately, not much."
 
-        elif echo "${CHATLINE}" | grep -E -i "(hello |hi |hey |heyo )" | grep -q "server"; then
-            if echo "${PLAYER}" | grep -E -q "(${OPS})"; then
+        elif echo "${chat_line}" | grep -E -i "(hello |hi |hey |heyo )" | grep -q "server"; then
+            if echo "${player}" | grep -E -q "(${ops})"; then
                 say "Hello there, Master."
             else
                 say "Hello there, little one."
             fi
     
-        elif echo "${CHATLINE}" | grep -i "you there" | grep -i -q "server"; then
-            if echo "${PLAYER}" | grep -E -q "(${OPS})"; then
+        elif echo "${chat_line}" | grep -i "you there" | grep -i -q "server"; then
+            if echo "${player}" | grep -E -q "(${ops})"; then
                 say "I am here, Master."
             else
                 say "Yes I am, watching your every move."
